### ISSUE TITLE
package consisting of multiple packages

### ISSUE THREAD

**Issue by belka-ew** [Dlackware/dlackware#10]
X11 build ends with an error since x11 package doesn't exist but contains several packages.
There are some possible solutions I can think about:
a) Split x11 in single packages
b) Install packages directly in the build script. The advantage would be that the build script is aware of all the data about the package, its path, name, version. We can use some variable like REINSTALL=no|yes|always to control if the packages should be only built, installed or reinstalled if needed.

Ideas?

**Comment by bartgymnast** [comment]
its only used in the build script anyway
so imo a notice (or an extra few lines of echo: like part 1 is done, blah blah, please continu to install systemd-service-files and gnome-systemd
